package hr.fer.tel.apsimx;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public class APSIMX_File {
    public static String WEATHER_FILE = "{\n"
            + "  \"$type\": \"Models.Core.Simulations, Models\",\n"
            + "  \"ExplorerWidth\": 300,\n"
            + "  \"Version\": 147,\n"
            + "  \"Name\": \"Simulations\",\n"
            + "  \"Children\": [\n"
            + "    {\n"
            + "      \"$type\": \"Models.Core.Simulation, Models\",\n"
            + "      \"IsRunning\": false,\n"
            + "      \"Descriptors\": null,\n"
            + "      \"Name\": \"Simulation\",\n"
            + "      \"Children\": [\n"
            + "        {\n"
            + "          \"$type\": \"Models.Clock, Models\",\n"
            + "          \"Start\": \""+getStartDateFormatted(-5)+"T00:00:00\",\n"
            + "          \"End\": \""+getEndDateFormatted(-1)+"T00:00:00\",\n"
            + "          \"Name\": \"Clock\",\n"
            + "          \"Children\": [],\n"
            + "          \"Enabled\": true,\n"
            + "          \"ReadOnly\": false\n"
            + "        },\n"
            + "        {\n"
            + "          \"$type\": \"Models.Summary, Models\",\n"
            + "          \"Verbosity\": 100,\n"
            + "          \"Name\": \"SummaryFile\",\n"
            + "          \"Children\": [],\n"
            + "          \"Enabled\": true,\n"
            + "          \"ReadOnly\": false\n"
            + "        },\n"
            + "        {\n"
            + "          \"$type\": \"Models.Climate.Weather, Models\",\n"
            + "          \"ConstantsFile\": null,\n"
            + "          \"FileName\": \"test.met\",\n"   //Change this!!!!!!!!!!!!!!!!!
            + "          \"ExcelWorkSheetName\": \"\",\n"
            + "          \"Name\": \"Weather\",\n"
            + "          \"Children\": [],\n"
            + "          \"Enabled\": true,\n"
            + "          \"ReadOnly\": false\n"
            + "        },\n"
            + "        {\n"
            + "          \"$type\": \"Models.Soils.Arbitrator.SoilArbitrator, Models\",\n"
            + "          \"Name\": \"Soil Arbitrator\",\n"
            + "          \"Children\": [],\n"
            + "          \"Enabled\": true,\n"
            + "          \"ReadOnly\": false\n"
            + "        },\n"
            + "        {\n"
            + "          \"$type\": \"Models.Core.Zone, Models\",\n"
            + "          \"Area\": 1.0,\n"
            + "          \"Slope\": 0.0,\n"
            + "          \"AspectAngle\": 0.0,\n"
            + "          \"Altitude\": 50.0,\n"
            + "          \"Name\": \"Field\",\n"
            + "          \"Children\": [\n"
            + "            {\n"
            + "              \"$type\": \"Models.Report, Models\",\n"
            + "              \"VariableNames\": [\n"
            + "                \"[Clock].Today\",\n"
            + "                \"[Weather].Radn\",\n"
            + "                \"[Weather].MaxT\",\n"
            + "                \"[Weather].MinT\",\n"
            + "                \"[Weather].Rain\",\n"
            + "                \"[Weather].Wind\"\n"
            + "              ],\n"
            + "              \"EventNames\": [\n"
            + "                \"[Clock].EndOfDay\"\n"
            + "              ],\n"
            + "              \"GroupByVariableName\": null,\n"
            + "              \"Name\": \"Report\",\n"
            + "              \"Children\": [],\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.Fertiliser, Models\",\n"
            + "              \"ResourceName\": \"Fertiliser\",\n"
            + "              \"Name\": \"Fertiliser\",\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.Soils.Soil, Models\",\n"
            + "              \"RecordNumber\": 0,\n"
            + "              \"ASCOrder\": \"Vertosol\",\n"
            + "              \"ASCSubOrder\": \"Black\",\n"
            + "              \"SoilType\": \"Clay\",\n"
            + "              \"LocalName\": null,\n"
            + "              \"Site\": \"Norwin\",\n"
            + "              \"NearestTown\": \"Norwin\",\n"
            + "              \"Region\": \"Darling Downs and Granite Belt\",\n"
            + "              \"State\": \"Queensland\",\n"
            + "              \"Country\": \"Australia\",\n"
            + "              \"NaturalVegetation\": \"Qld. Bluegrass, possible Qld. Blue gum\",\n"
            + "              \"ApsoilNumber\": \"900\",\n"
            + "              \"Latitude\": -27.581836,\n"
            + "              \"Longitude\": 151.320206,\n"
            + "              \"LocationAccuracy\": \" +/- 20m\",\n"
            + "              \"YearOfSampling\": null,\n"
            + "              \"DataSource\": \"CSIRO Sustainable Ecosystems, Toowoomba; Characteriesd as part of the GRDC funded project\\\"Doing it better, doing it smarter, managing soil water in Australian agriculture' 2011\",\n"
            + "              \"Comments\": \"OC, CLL for all crops estimated-based on Bongeen Mywybilla Soil No1\",\n"
            + "              \"Name\": \"Soil\",\n"
            + "              \"Children\": [\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.Physical, Models\",\n"
            + "                  \"Depth\": [\n"
            + "                    \"0-15\",\n"
            + "                    \"15-30\",\n"
            + "                    \"30-60\",\n"
            + "                    \"60-90\",\n"
            + "                    \"90-120\",\n"
            + "                    \"120-150\",\n"
            + "                    \"150-180\"\n"
            + "                  ],\n"
            + "                  \"Thickness\": [\n"
            + "                    150.0,\n"
            + "                    150.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0\n"
            + "                  ],\n"
            + "                  \"ParticleSizeClay\": null,\n"
            + "                  \"ParticleSizeSand\": null,\n"
            + "                  \"ParticleSizeSilt\": null,\n"
            + "                  \"Rocks\": null,\n"
            + "                  \"Texture\": null,\n"
            + "                  \"BD\": [\n"
            + "                    1.01056473311131,\n"
            + "                    1.07145631083388,\n"
            + "                    1.09393858528057,\n"
            + "                    1.15861335018721,\n"
            + "                    1.17301160318016,\n"
            + "                    1.16287303586874,\n"
            + "                    1.18749547755906\n"
            + "                  ],\n"
            + "                  \"AirDry\": [\n"
            + "                    0.130250054518252,\n"
            + "                    0.198689390775399,\n"
            + "                    0.28,\n"
            + "                    0.28,\n"
            + "                    0.28,\n"
            + "                    0.28,\n"
            + "                    0.28\n"
            + "                  ],\n"
            + "                  \"LL15\": [\n"
            + "                    0.260500109036505,\n"
            + "                    0.248361738469248,\n"
            + "                    0.28,\n"
            + "                    0.28,\n"
            + "                    0.28,\n"
            + "                    0.28,\n"
            + "                    0.28\n"
            + "                  ],\n"
            + "                  \"DUL\": [\n"
            + "                    0.52100021807301,\n"
            + "                    0.496723476938497,\n"
            + "                    0.488437607673005,\n"
            + "                    0.480296969355493,\n"
            + "                    0.471583596524955,\n"
            + "                    0.457070570557793,\n"
            + "                    0.452331759845006\n"
            + "                  ],\n"
            + "                  \"SAT\": [\n"
            + "                    0.588654817693846,\n"
            + "                    0.565676863836273,\n"
            + "                    0.557192986686577,\n"
            + "                    0.532787415023694,\n"
            + "                    0.527354112007486,\n"
            + "                    0.531179986464627,\n"
            + "                    0.521888499034317\n"
            + "                  ],\n"
            + "                  \"KS\": [\n"
            + "                    20.0,\n"
            + "                    20.0,\n"
            + "                    20.0,\n"
            + "                    20.0,\n"
            + "                    20.0,\n"
            + "                    20.0,\n"
            + "                    20.0\n"
            + "                  ],\n"
            + "                  \"BDMetadata\": null,\n"
            + "                  \"AirDryMetadata\": null,\n"
            + "                  \"LL15Metadata\": null,\n"
            + "                  \"DULMetadata\": null,\n"
            + "                  \"SATMetadata\": null,\n"
            + "                  \"KSMetadata\": null,\n"
            + "                  \"RocksMetadata\": null,\n"
            + "                  \"TextureMetadata\": null,\n"
            + "                  \"ParticleSizeSandMetadata\": null,\n"
            + "                  \"ParticleSizeSiltMetadata\": null,\n"
            + "                  \"ParticleSizeClayMetadata\": null,\n"
            + "                  \"Name\": \"Physical\",\n"
            + "                  \"Children\": [\n"
            + "                    {\n"
            + "                      \"$type\": \"Models.Soils.SoilCrop, Models\",\n"
            + "                      \"LL\": [\n"
            + "                        0.261,\n"
            + "                        0.248,\n"
            + "                        0.28,\n"
            + "                        0.306,\n"
            + "                        0.36,\n"
            + "                        0.392,\n"
            + "                        0.446\n"
            + "                      ],\n"
            + "                      \"KL\": [\n"
            + "                        0.06,\n"
            + "                        0.06,\n"
            + "                        0.06,\n"
            + "                        0.04,\n"
            + "                        0.04,\n"
            + "                        0.02,\n"
            + "                        0.01\n"
            + "                      ],\n"
            + "                      \"XF\": [\n"
            + "                        1.0,\n"
            + "                        1.0,\n"
            + "                        1.0,\n"
            + "                        1.0,\n"
            + "                        1.0,\n"
            + "                        1.0,\n"
            + "                        1.0\n"
            + "                      ],\n"
            + "                      \"LLMetadata\": null,\n"
            + "                      \"KLMetadata\": null,\n"
            + "                      \"XFMetadata\": null,\n"
            + "                      \"Name\": \"MaizeSoil\",\n"
            + "                      \"Children\": [],\n"
            + "                      \"Enabled\": true,\n"
            + "                      \"ReadOnly\": false\n"
            + "                    }\n"
            + "                  ],\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.WaterModel.WaterBalance, Models\",\n"
            + "                  \"SummerDate\": \"1-Nov\",\n"
            + "                  \"SummerU\": 5.0,\n"
            + "                  \"SummerCona\": 5.0,\n"
            + "                  \"WinterDate\": \"1-Apr\",\n"
            + "                  \"WinterU\": 5.0,\n"
            + "                  \"WinterCona\": 5.0,\n"
            + "                  \"DiffusConst\": 40.0,\n"
            + "                  \"DiffusSlope\": 16.0,\n"
            + "                  \"Salb\": 0.12,\n"
            + "                  \"CN2Bare\": 73.0,\n"
            + "                  \"CNRed\": 20.0,\n"
            + "                  \"CNCov\": 0.8,\n"
            + "                  \"DischargeWidth\": \"NaN\",\n"
            + "                  \"CatchmentArea\": \"NaN\",\n"
            + "                  \"Thickness\": [\n"
            + "                    150.0,\n"
            + "                    150.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0\n"
            + "                  ],\n"
            + "                  \"SWCON\": [\n"
            + "                    0.3,\n"
            + "                    0.3,\n"
            + "                    0.3,\n"
            + "                    0.3,\n"
            + "                    0.3,\n"
            + "                    0.3,\n"
            + "                    0.3\n"
            + "                  ],\n"
            + "                  \"KLAT\": null,\n"
            + "                  \"ResourceName\": \"WaterBalance\",\n"
            + "                  \"Name\": \"SoilWater\",\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.Organic, Models\",\n"
            + "                  \"Depth\": [\n"
            + "                    \"0-15\",\n"
            + "                    \"15-30\",\n"
            + "                    \"30-60\",\n"
            + "                    \"60-90\",\n"
            + "                    \"90-120\",\n"
            + "                    \"120-150\",\n"
            + "                    \"150-180\"\n"
            + "                  ],\n"
            + "                  \"FOMCNRatio\": 40.0,\n"
            + "                  \"Thickness\": [\n"
            + "                    150.0,\n"
            + "                    150.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0\n"
            + "                  ],\n"
            + "                  \"Carbon\": [\n"
            + "                    1.2,\n"
            + "                    0.96,\n"
            + "                    0.6,\n"
            + "                    0.3,\n"
            + "                    0.18,\n"
            + "                    0.12,\n"
            + "                    0.12\n"
            + "                  ],\n"
            + "                  \"SoilCNRatio\": [\n"
            + "                    12.0,\n"
            + "                    12.0,\n"
            + "                    12.0,\n"
            + "                    12.0,\n"
            + "                    12.0,\n"
            + "                    12.0,\n"
            + "                    12.0\n"
            + "                  ],\n"
            + "                  \"FBiom\": [\n"
            + "                    0.04,\n"
            + "                    0.02,\n"
            + "                    0.02,\n"
            + "                    0.02,\n"
            + "                    0.01,\n"
            + "                    0.01,\n"
            + "                    0.01\n"
            + "                  ],\n"
            + "                  \"FInert\": [\n"
            + "                    0.4,\n"
            + "                    0.6,\n"
            + "                    0.8,\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0\n"
            + "                  ],\n"
            + "                  \"FOM\": [\n"
            + "                    347.1290323127564,\n"
            + "                    270.3443621919937,\n"
            + "                    163.97214434990104,\n"
            + "                    99.45413288704063,\n"
            + "                    60.32198083112468,\n"
            + "                    36.58713082867487,\n"
            + "                    22.1912165985086\n"
            + "                  ],\n"
            + "                  \"CarbonMetadata\": null,\n"
            + "                  \"FOMMetadata\": null,\n"
            + "                  \"Name\": \"Organic\",\n"
            + "                  \"Children\": [],\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.Chemical, Models\",\n"
            + "                  \"Depth\": [\n"
            + "                    \"0-15\",\n"
            + "                    \"15-30\",\n"
            + "                    \"30-60\",\n"
            + "                    \"60-90\",\n"
            + "                    \"90-120\",\n"
            + "                    \"120-150\",\n"
            + "                    \"150-180\"\n"
            + "                  ],\n"
            + "                  \"Thickness\": [\n"
            + "                    150.0,\n"
            + "                    150.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0\n"
            + "                  ],\n"
            + "                  \"NO3N\": [\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0,\n"
            + "                    1.0\n"
            + "                  ],\n"
            + "                  \"NH4N\": [\n"
            + "                    0.1,\n"
            + "                    0.1,\n"
            + "                    0.1,\n"
            + "                    0.1,\n"
            + "                    0.1,\n"
            + "                    0.1,\n"
            + "                    0.1\n"
            + "                  ],\n"
            + "                  \"PH\": [\n"
            + "                    8.0,\n"
            + "                    8.0,\n"
            + "                    8.0,\n"
            + "                    8.0,\n"
            + "                    8.0,\n"
            + "                    8.0,\n"
            + "                    8.0\n"
            + "                  ],\n"
            + "                  \"CL\": null,\n"
            + "                  \"EC\": null,\n"
            + "                  \"ESP\": null,\n"
            + "                  \"LabileP\": null,\n"
            + "                  \"UnavailableP\": null,\n"
            + "                  \"ECMetadata\": null,\n"
            + "                  \"CLMetadata\": null,\n"
            + "                  \"ESPMetadata\": null,\n"
            + "                  \"PHMetadata\": null,\n"
            + "                  \"Name\": \"Chemical\",\n"
            + "                  \"Children\": [],\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.InitialWater, Models\",\n"
            + "                  \"PercentMethod\": 1,\n"
            + "                  \"FractionFull\": 1.0,\n"
            + "                  \"DepthWetSoil\": \"NaN\",\n"
            + "                  \"RelativeTo\": null,\n"
            + "                  \"Name\": \"InitialWater\",\n"
            + "                  \"Children\": [],\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.Sample, Models\",\n"
            + "                  \"Depth\": [\n"
            + "                    \"0-15\",\n"
            + "                    \"15-30\",\n"
            + "                    \"30-60\",\n"
            + "                    \"60-90\",\n"
            + "                    \"90-120\",\n"
            + "                    \"120-150\",\n"
            + "                    \"150-180\"\n"
            + "                  ],\n"
            + "                  \"Thickness\": [\n"
            + "                    150.0,\n"
            + "                    150.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0,\n"
            + "                    300.0\n"
            + "                  ],\n"
            + "                  \"NO3\": null,\n"
            + "                  \"NH4\": null,\n"
            + "                  \"LabileP\": null,\n"
            + "                  \"UnavailableP\": null,\n"
            + "                  \"SW\": [\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\"\n"
            + "                  ],\n"
            + "                  \"OC\": [\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\"\n"
            + "                  ],\n"
            + "                  \"EC\": [\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\"\n"
            + "                  ],\n"
            + "                  \"CL\": [\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\"\n"
            + "                  ],\n"
            + "                  \"ESP\": [\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\"\n"
            + "                  ],\n"
            + "                  \"PH\": [\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\",\n"
            + "                    \"NaN\"\n"
            + "                  ],\n"
            + "                  \"SWUnits\": 0,\n"
            + "                  \"OCUnits\": 0,\n"
            + "                  \"PHUnits\": 0,\n"
            + "                  \"Name\": \"InitialN\",\n"
            + "                  \"Children\": [],\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.CERESSoilTemperature, Models\",\n"
            + "                  \"Name\": \"Temperature\",\n"
            + "                  \"Children\": [],\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                },\n"
            + "                {\n"
            + "                  \"$type\": \"Models.Soils.Nutrients.Nutrient, Models\",\n"
            + "                  \"ResourceName\": \"Nutrient\",\n"
            + "                  \"Name\": \"Nutrient\",\n"
            + "                  \"Enabled\": true,\n"
            + "                  \"ReadOnly\": false\n"
            + "                }\n"
            + "              ],\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.Surface.SurfaceOrganicMatter, Models\",\n"
            + "              \"InitialResidueName\": \"wheat_stubble\",\n"
            + "              \"InitialResidueType\": \"wheat\",\n"
            + "              \"InitialResidueMass\": 500.0,\n"
            + "              \"InitialStandingFraction\": 0.0,\n"
            + "              \"InitialCPR\": 0.0,\n"
            + "              \"InitialCNR\": 100.0,\n"
            + "              \"ResourceName\": \"SurfaceOrganicMatter\",\n"
            + "              \"Name\": \"SurfaceOrganicMatter\",\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.PMF.Plant, Models\",\n"
            + "              \"ResourceName\": \"Maize\",\n"
            + "              \"Name\": \"Maize\",\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.MicroClimate, Models\",\n"
            + "              \"a_interception\": 0.0,\n"
            + "              \"b_interception\": 1.0,\n"
            + "              \"c_interception\": 0.0,\n"
            + "              \"d_interception\": 0.0,\n"
            + "              \"SoilHeatFluxFraction\": 0.4,\n"
            + "              \"MinimumHeightDiffForNewLayer\": 0.0,\n"
            + "              \"NightInterceptionFraction\": 0.5,\n"
            + "              \"ReferenceHeight\": 2.0,\n"
            + "              \"Name\": \"MicroClimate\",\n"
            + "              \"Children\": [],\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.Manager, Models\",\n"
            + "              \"Code\": \"using Models.PMF;\\r\\nusing Models.Core;\\r\\nusing System;\\r\\nnamespace Models\\r\\n{\\r\\n    [Serializable]\\r\\n    public class Script : Model\\r\\n    {\\r\\n        [Link] Clock Clock;\\r\\n        [Link] Fertiliser Fertiliser;\\r\\n        [Link] Summary Summary;\\r\\n        \\r\\n        \\r\\n        [Description(\\\"Amount of fertiliser to be applied (kg/ha)\\\")]\\r\\n        public double Amount { get; set; }\\r\\n        \\r\\n        [Description(\\\"Crop to be fertilised\\\")]\\r\\n        public string CropName { get; set; }\\r\\n        \\r\\n        \\r\\n        \\r\\n\\r\\n        [EventSubscribe(\\\"Sowing\\\")]\\r\\n        private void OnSowing(object sender, EventArgs e)\\r\\n        {\\r\\n            Model crop = sender as Model;\\r\\n            if (crop.Name.ToLower() == CropName.ToLower())\\r\\n                Fertiliser.Apply(Amount: Amount, Type: Fertiliser.Types.NO3N);\\r\\n        }\\r\\n        \\r\\n    }\\r\\n}\\r\\n\",\n"
            + "              \"Parameters\": [\n"
            + "                {\n"
            + "                  \"Key\": \"Amount\",\n"
            + "                  \"Value\": \"160\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"CropName\",\n"
            + "                  \"Value\": \"maize\"\n"
            + "                }\n"
            + "              ],\n"
            + "              \"Name\": \"SowingFertiliser\",\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.Manager, Models\",\n"
            + "              \"Code\": \"using Models.Interfaces;\\r\\nusing System;\\r\\nusing Models.Core;\\r\\nusing Models.PMF;\\r\\nusing Models.Soils;\\r\\nusing Models.Soils.Nutrients;\\r\\nusing Models.Utilities;\\r\\nusing APSIM.Shared.Utilities;\\r\\nusing Models.Climate;\\r\\n\\r\\nnamespace Models\\r\\n{\\r\\n    [Serializable]\\r\\n    public class Script : Model\\r\\n    {\\r\\n        [Link] private Clock Clock;\\r\\n        [Link] private Fertiliser Fertiliser;\\r\\n        [Link] private Summary Summary;\\r\\n        [Link(ByName = true)] private Plant Maize;\\r\\n        [Link] private Soil Soil;\\r\\n        private Accumulator accumulatedRain;\\r\\n        [Link]\\r\\n        private ISoilWater waterBalance;\\r\\n        \\r\\n        [Description(\\\"Start of sowing window (d-mmm)\\\")]\\r\\n        public string StartDate { get; set; }\\r\\n        [Description(\\\"End of sowing window (d-mmm)\\\")]\\r\\n        public string EndDate { get; set; }\\r\\n        [Description(\\\"Minimum extractable soil water for sowing (mm)\\\")]\\r\\n        public double MinESW { get; set; }\\r\\n        [Description(\\\"Accumulated rainfall required for sowing (mm)\\\")]\\r\\n        public double MinRain { get; set; }\\r\\n        [Description(\\\"Duration of rainfall accumulation (d)\\\")]\\r\\n        public int RainDays { get; set; }\\r\\n        [Description(\\\"Cultivar to be sown\\\")]\\r\\n        [Display(Type=DisplayType.CultivarName, PlantName = \\\"Maize\\\")]\\r\\n        public string CultivarName { get; set; }\\r\\n        [Description(\\\"Sowing depth (mm)\\\")]\\r\\n        public double SowingDepth { get; set; }\\r\\n        [Description(\\\"Row spacing (mm)\\\")]\\r\\n        public double RowSpacing { get; set; }\\r\\n        [Description(\\\"Plant population (/m2)\\\")]\\r\\n        public double Population { get; set; }\\r\\n        \\r\\n        \\r\\n        [EventSubscribe(\\\"StartOfSimulation\\\")]\\r\\n        private void OnSimulationCommencing(object sender, EventArgs e)\\r\\n        {\\r\\n            accumulatedRain = new Accumulator(this, \\\"[Weather].Rain\\\", RainDays);\\r\\n        }\\r\\n        \\r\\n\\r\\n        [EventSubscribe(\\\"DoManagement\\\")]\\r\\n        private void OnDoManagement(object sender, EventArgs e)\\r\\n        {\\r\\n            accumulatedRain.Update();\\r\\n            \\r\\n            if (DateUtilities.WithinDates(StartDate, Clock.Today, EndDate) &&\\r\\n                !Maize.IsAlive &&\\r\\n                MathUtilities.Sum(waterBalance.ESW) > MinESW &&\\r\\n                accumulatedRain.Sum > MinRain)\\r\\n            {\\r\\n                Maize.Sow(population: Population, cultivar: CultivarName, depth: SowingDepth, rowSpacing: RowSpacing);    \\r\\n            }\\r\\n        \\r\\n        }\\r\\n        \\r\\n    }\\r\\n}\\r\\n\",\n"
            + "              \"Parameters\": [\n"
            + "                {\n"
            + "                  \"Key\": \"StartDate\",\n"
            + "                  \"Value\": \"1-nov\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"EndDate\",\n"
            + "                  \"Value\": \"10-jan\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"MinESW\",\n"
            + "                  \"Value\": \"100\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"MinRain\",\n"
            + "                  \"Value\": \"25\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"RainDays\",\n"
            + "                  \"Value\": \"7\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"CultivarName\",\n"
            + "                  \"Value\": \"Dekalb_XL82\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"SowingDepth\",\n"
            + "                  \"Value\": \"30\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"RowSpacing\",\n"
            + "                  \"Value\": \"750\"\n"
            + "                },\n"
            + "                {\n"
            + "                  \"Key\": \"Population\",\n"
            + "                  \"Value\": \"6\"\n"
            + "                }\n"
            + "              ],\n"
            + "              \"Name\": \"SowingRule\",\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"Models.Manager, Models\",\n"
            + "              \"Code\": \"using Models.PMF.Phen;\\r\\nusing APSIM.Shared.Utilities;\\r\\nusing System.Xml.Serialization;\\r\\nusing Models;\\r\\nusing Models.PMF;\\r\\nusing Models.Soils;\\r\\nusing System.Text;\\r\\nusing System.Collections.Generic;\\r\\nusing Models.Core;\\r\\nusing System;\\r\\nusing Models.Soils.Nutrients;\\r\\n\\r\\nnamespace Models\\r\\n{\\r\\n    [Serializable] \\r\\n    public class Script : Model\\r\\n    {\\r\\n        [Link(ByName = true)] private Plant Maize;\\r\\n        [Link] private Zone zone;\\r\\n        [Link(Type = LinkType.Path, Path = \\\"[Maize].Phenology\\\")]\\r\\n        private Phenology phenology;\\r\\n                    \\r\\n        \\r\\n        [EventSubscribe(\\\"StartOfSimulation\\\")]\\r\\n        private void OnSimulationCommencing(object sender, EventArgs e)\\r\\n        {\\r\\n        }\\r\\n        \\r\\n        [EventSubscribe(\\\"DoManagement\\\")]\\r\\n        private void OnDoManagement(object sender, EventArgs e)\\r\\n        {\\r\\n            if (phenology.CurrentPhase.Name == \\\"ReadyForHarvesting\\\")\\r\\n            {\\r\\n                Maize.Harvest();\\r\\n                Maize.EndCrop();\\r\\n            }\\r\\n        }\\r\\n        \\r\\n        [EventSubscribe(\\\"DoManagementCalculations\\\")]\\r\\n        private void OnDoManagementCalculations(object sender, EventArgs e)\\r\\n        {\\r\\n            \\r\\n        }\\r\\n    }\\r\\n}\\r\\n       \\r\\n\",\n"
            + "              \"Parameters\": [],\n"
            + "              \"Name\": \"Harvesting\",\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            }\n"
            + "          ],\n"
            + "          \"Enabled\": true,\n"
            + "          \"ReadOnly\": false\n"
            + "        },\n"
            + "        {\n"
            + "          \"$type\": \"Models.Graph, Models\",\n"
            + "          \"Caption\": null,\n"
            + "          \"Axis\": [\n"
            + "            {\n"
            + "              \"$type\": \"APSIM.Shared.Graphing.Axis, APSIM.Shared\",\n"
            + "              \"Title\": \"Date\",\n"
            + "              \"Position\": 3,\n"
            + "              \"Inverted\": false,\n"
            + "              \"CrossesAtZero\": false,\n"
            + "              \"Minimum\": null,\n"
            + "              \"Maximum\": null,\n"
            + "              \"Interval\": null\n"
            + "            },\n"
            + "            {\n"
            + "              \"$type\": \"APSIM.Shared.Graphing.Axis, APSIM.Shared\",\n"
            + "              \"Title\": null,\n"
            + "              \"Position\": 0,\n"
            + "              \"Inverted\": false,\n"
            + "              \"CrossesAtZero\": false,\n"
            + "              \"Minimum\": null,\n"
            + "              \"Maximum\": null,\n"
            + "              \"Interval\": null\n"
            + "            }\n"
            + "          ],\n"
            + "          \"LegendPosition\": 0,\n"
            + "          \"LegendOrientation\": 0,\n"
            + "          \"AnnotationLocation\": 0,\n"
            + "          \"DisabledSeries\": [],\n"
            + "          \"LegendOutsideGraph\": false,\n"
            + "          \"Name\": \"Maize Yield Time Series\",\n"
            + "          \"Children\": [\n"
            + "            {\n"
            + "              \"$type\": \"Models.Series, Models\",\n"
            + "              \"Type\": 1,\n"
            + "              \"XAxis\": 3,\n"
            + "              \"YAxis\": 0,\n"
            + "              \"ColourArgb\": -16776961,\n"
            + "              \"FactorToVaryColours\": null,\n"
            + "              \"FactorToVaryMarkers\": null,\n"
            + "              \"FactorToVaryLines\": null,\n"
            + "              \"Marker\": 0,\n"
            + "              \"MarkerSize\": 0,\n"
            + "              \"Line\": 0,\n"
            + "              \"LineThickness\": 0,\n"
            + "              \"TableName\": \"Report\",\n"
            + "              \"XFieldName\": \"Clock.Today\",\n"
            + "              \"YFieldName\": \"Maize.Grain.Wt\",\n"
            + "              \"X2FieldName\": \"\",\n"
            + "              \"Y2FieldName\": \"\",\n"
            + "              \"ShowInLegend\": true,\n"
            + "              \"IncludeSeriesNameInLegend\": false,\n"
            + "              \"Cumulative\": false,\n"
            + "              \"CumulativeX\": false,\n"
            + "              \"Filter\": null,\n"
            + "              \"Name\": \"Maize Yield\",\n"
            + "              \"Children\": [],\n"
            + "              \"Enabled\": true,\n"
            + "              \"ReadOnly\": false\n"
            + "            }\n"
            + "          ],\n"
            + "          \"Enabled\": true,\n"
            + "          \"ReadOnly\": false\n"
            + "        }\n"
            + "      ],\n"
            + "      \"Enabled\": true,\n"
            + "      \"ReadOnly\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"$type\": \"Models.Storage.DataStore, Models\",\n"
            + "      \"useFirebird\": false,\n"
            + "      \"CustomFileName\": null,\n"
            + "      \"Name\": \"DataStore\",\n"
            + "      \"Children\": [],\n"
            + "      \"Enabled\": true,\n"
            + "      \"ReadOnly\": false\n"
            + "    }\n"
            + "  ],\n"
            + "  \"Enabled\": true,\n"
            + "  \"ReadOnly\": false\n"
            + "}";

    private static String getStartDateFormatted(int index){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar year = Calendar.getInstance();
        year.add(Calendar.YEAR, index);
        return dateFormat.format(year.getTime());
    }

    private static Date getDate(int index) {
        final Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, index);
        return cal.getTime();
    }

    private static String getEndDateFormatted(int index) {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat.format(getDate(index));
    }
}
